# Generated by Django 5.2 on 2025-04-30 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0002_pedido_data_criacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('P', 'Pendente'), ('E', 'Entregue')], default='P', max_length=1),
        ),
    ]
