# Generated by Django 5.2 on 2025-04-30 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0003_alter_pedido_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='prato',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='quantidade',
        ),
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('P', 'Pendente'), ('C', 'Concluído')], default='P', max_length=20),
        ),
        migrations.CreateModel(
            name='PedidoPrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField()),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pratos', to='restaurante.pedido')),
                ('prato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurante.prato')),
            ],
        ),
    ]
