# Generated by Django 5.2 on 2025-04-28 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Prato',
            fields=[
                ('id_prato', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('nome', models.CharField(max_length=100)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ingrediente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='restaurante.ingrediente')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantidade', models.PositiveIntegerField()),
                ('data_pedido', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('P', 'Pendente'), ('C', 'Concluído')], default='P', max_length=20)),
                ('prato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='restaurante.prato')),
            ],
        ),
        migrations.CreateModel(
            name='PratoIngrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.FloatField()),
                ('ingrediente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurante.ingrediente')),
                ('prato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurante.prato')),
            ],
        ),
        migrations.AddField(
            model_name='prato',
            name='ingredientes',
            field=models.ManyToManyField(related_name='pratos', through='restaurante.PratoIngrediente', to='restaurante.ingrediente'),
        ),
    ]
